---
design:
  groups:
    #input: 'design_matrix.csv'
    #alternative_module: ['generate_groups_alt','gen_measurement_matrix_alt']
    params:
      seed: 10
      N: 1000
      'm': 500
      'verbose': False
      'run_ID': 'debugging'
      'plotting': False
      'saving': True
      'graph_gen_method': 'no_multiple'
      'group_size':
        'mode': 'list'
        'values': [8,16]
      'max_tests_per_individual':
        'mode': 'list'
        'values': [16]
      'save_to_file': True
  'individual_status':
    #input: 'individual_status.csv'
    params:
      seed: 10
      'verbose': False
      's':
        'mode': 'list'
        'values': [50]
  'test_results':
    #'input': 'test_results.csv'
    'params':
      'test_noise_methods': ['permutation']
      'permutation_noise_prob':
        'mode': 'list'
        'values': [0.01]
      'theta_l':
        'mode': 'list'
        'values': [0.00]
      'theta_u':
        'mode': 'list'
        'values': [0.0625]
      'binary_symmetric_noise_prob':
        'mode': 'list'
        'values': [0.26]

decode:
  'decoder':
    #alternative_module: ['group_testing_decoder','GroupTestingDecoder']
    params:
      'lambda_w': 1
      'lambda_e': 4
      'defective_num_lower_bound': null
      'sensitivity_threshold': null
      'specificity_threshold': null
      'is_it_noiseless': False
      'lp_relaxation': False
      'solver_name': 'CPLEX_PY'
      'solver_options':
        'timeLimit': 1800
      'lambda_selection': True
      'number_of_folds': 3
      'cv_param':
        'lambda_e': [0.125,0.25,0.5,1,2,4,8]
    #'mip':True
  'evaluation':
    #'eval_metric': 'recall'
    'eval_metric': 'balanced_accuracy'
