---
opts:
  'run_ID': 'debugging'
  'verbose': False
  'plotting': False
  'saving': True
  'graph_gen_method': 'no_multiple'
  'test_noise_methods': ['permutation']
  'permutation_noise_prob':
    'mode': 'scalar'
    'values': [0.01]
  'theta_l':
    'mode': 'scalar'
    'values': [0.00]
  'theta_u':
    'mode': 'scalar'
    'values': [0.0625]
  'binary_symmetric_noise_prob':
    'mode': 'scalar'
    'values': [0.26]
  'seed':
    'mode': 'range'
    'values': [0,10,1]
  'N':
    'mode': 'scalar'
    'values': [1000]
  's':
    'mode': 'scalar'
    'values': [50]
  'group_size':
    'mode': 'scalar'
    'values': [16]
  'm':
    'mode': 'range'
    'values': [10,1010,10]
  'max_tests_per_individual':
    'mode': 'scalar'
    'values': [16]

lambda_selection:
  'cross_validation': True
  'number_of_folds': 5
  'param':
    'lambda_p': [0.125,0.25,0.5,1,2,4,8]
    'lambda_n': [0.125,0.25,0.5,1,2,4,8]

param:
  'lambda_w': 1
  'lambda_p': 100
  'lambda_n': 100
  'defective_num_lower_bound': null
  'sensitivity_threshold': null
  'specificity_threshold': null
  'is_it_noiseless': True
  'lp_relaxation': False
  'solver_name': 'CPLEX_PY'
  'solver_options':
    'mode': 'exact'
    'timeLimit': 1800
