---
design_param:
  'general':
    'seed':
      'mode': 'range'
      'values': [0,1,1]
    'N':
      'mode': 'scalar'
      'values': [1000]
    'm':
      'mode': 'range'
      'values': [10,30,10]
    'verbose': False
  'generate_groups':
    'run_ID': 'debugging'
    'plotting': False
    'saving': True
    'graph_gen_method': 'no_multiple'
    'group_size':
      'mode': 'scalar'
      'values': [16]
    'max_tests_per_individual':
      'mode': 'scalar'
      'values': [16]
  'generate_individual_status':
    's':
      'mode': 'scalar'
      'values': [50]
  'generate_test_results':
    'test_noise_methods': ['permutation']
    'permutation_noise_prob':
      'mode': 'scalar'
      'values': [0.01]
    'theta_l':
      'mode': 'scalar'
      'values': [0.00]
    'theta_u':
      'mode': 'scalar'
      'values': [0.0625]
    'binary_symmetric_noise_prob':
      'mode': 'scalar'
      'values': [0.26]

decoder_param:
  'decode':
    'lambda_w': 1
    'lambda_e':
      'mode': 'scalar'
      'values': [0.125,0.25,0.5,1,2,4,8]
    'defective_num_lower_bound': null
    'sensitivity_threshold': null
    'specificity_threshold': null
    'is_it_noiseless': False
    'lp_relaxation': False
    'solver_name': 'CPLEX_PY'
    'solver_options':
      'mode': 'exact'
      'timeLimit': 1800
  'lambda_selection':
    'cross_validation': False
    'number_of_folds': 2
    'cv_param':
      'mode': 'exact'
      'lambda_e': [0.125,0.25,0.5,1,2,4,8]
    #'mip':True
  'evaluation':
    'eval_metric': 'balanced_accuracy'

