---
opts:
  'run_ID': 'debugging'
  'verbose': False
  'plotting': False
  'saving': True
  'graph_gen_method': 'no_multiple'
  'test_noise_methods': []
  'seed':
    'mode': 'continuous'
    'values': [0,1,1]
  'N':
    'mode': 'discrete'
    'values': [10]
  's':
    'mode': 'discrete'

    'values': [100]
  'group_size':
    'mode': 'discrete'
    'values': [6]
  'm':
    'mode': 'discrete'
    'values': [5]
  'max_tests_per_individual':
    'mode': 'discrete'
    'values': [6]

param:
  'lambda_w': 1
  'lambda_p': 100
  'lambda_n': 100
  'defective_num_lower_bound': null
  'sensitivity_threshold': null
  'specificity_threshold': null
  'is_it_noiseless': True
  'lp_relaxation': False
  'solver_name': 'CPLEX_PY'
  'solver_options':
    'mode': 'exact'
    'timeLimit': 1800
