---
design:
  groups:
    #input: 'design_matrix.csv'
    #alternative_module: ['generate_groups_alt','gen_measurement_matrix_alt']
    params:
      seed:
        mode: 'range'
        values: [0,2,1]
      N: 1000
      'm': 500
      'verbose': False
      'graph_gen_method': 'no_multiple'
      'group_size': 8
#        mode: 'range'
#        values: [8,18,2]
      'max_tests_per_individual':
        'mode': 'list'
        'values': [16]
      'save_to_file': True
  'individual_status':
    #input: 'individual_status.csv'
    params:
      's':
        'mode': 'list'
        'values': [100]
  'test_results':
    #'input': 'test_results.csv'
    'params':
      seed: 20
      'verbose': False
      'test_noise_methods': []
      'permutation_noise_prob':
        'mode': 'list'
        'values': [0.01]
      'theta_l':
        'mode': 'list'
        'values': [0.00]
      'theta_u':
        'mode': 'list'
        'values': [0.0625]
      'binary_symmetric_noise_prob':
        'mode': 'list'
        'values': [0.26]

decode:
  'decoder':
    #alternative_module: ['group_testing_decoder','GroupTestingDecoder']
    params:
      'lambda_e': 4
      'is_it_noiseless': True
      'lp_relaxation': False
      'solver_name': 'CPLEX_PY'
      #['GLPK_CMD', 'CPLEX_PY', 'GUROBI_CMD', 'PULP_CBC_CMD', 'COIN_CMD', 'PULP_CHOCO_CMD']
      'solver_options':
        'timeLimit': 1800
        'logPath': 'auto'
      'lambda_selection': False
      'number_of_folds': 3
      'cv_param':
        'lambda_e': [0.125,0.25,0.5,1,2,4,8]
    #'mip':True
  'evaluation':
    #'eval_metric': 'recall'
    'eval_metric': 'balanced_accuracy'
